# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Momentum Mod
title: Momentum Mod Documentation
email: team@momentum-mod.org
description: >- # this means to ignore newlines until "baseurl:"
  Momentum Mod documentation; console commands, variables, and guides!
minimal_mistakes_skin: dark
search: true
repository: momentum-mod/docs
url: "https://docs.momentum-mod.org"
logo: "/assets/images/masthead.png"
masthead_title: Documentation

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/V4gS7Qg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/momentum-mod"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MomentumMod"

defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: "sidebar"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Scripts
after_footer_scripts:
  - /assets/js/autoscroll.js
