name: ✍ Updating Documentation
description: Something needs to be updated.
labels: ["update"]
body:
- type: textarea
  attributes:
    label: Describe what needs updated
    description: A clear and concise description of what needs updating.
    placeholder: X has confusing/little documentation.
  validations:
    required: true
- type: textarea
  attributes:
    label: What needs changed
    description: Describe what needs to be changed/added to the page.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about what needs updated here.
  validations:
    required: false
